### ISSUE TITLE
Terms

### ISSUE THREAD

**Issue by KhanEmo** [affinate/RedditAccountCreator#1]
Hi, I'm Alexander Kim I currently work as a reddit employee https://www.linkedin.com/in/alexanderkkim/ and what you did here is violating our terms and conditions.
We don't want bots on our platform. I want you to remove (private) this repository. Thanks for your understanding

**Comment by affinate** [comment]
Hey Alexander,
I understand your concerns but as stated in the `README.md` this repository is for educational purposes only and I don't encourage anyone to create bots with it. Having that said this repository will remain being public as I want to show others how selenium works.
